In [1]:
import numpy as np

In [2]:
data=np.random.randn(2,3)

In [3]:
data

array([[-0.19208164, -0.2490293 ,  1.29998543],
       [ 0.90716801, -0.86288578, -0.6635985 ]])

In [4]:
data

array([[-0.19208164, -0.2490293 ,  1.29998543],
       [ 0.90716801, -0.86288578, -0.6635985 ]])

In [5]:
data1=np.random.randn(2,3)

In [6]:
data1

array([[-0.93555359, -0.95621538, -0.4810742 ],
       [-0.14586391, -1.26037554, -0.02642326]])

In [7]:
data*10

array([[-1.92081635, -2.49029298, 12.99985433],
       [ 9.07168009, -8.62885778, -6.63598504]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data2=[6,7.5,8,0,1]

In [11]:
arr1=np.array(data2)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data3=[[1,2,3,4],[5,6,7,8]]

In [15]:
arr2=np.array(data3)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
data.dtype

dtype('float64')

In [18]:
data.shape

(2, 3)

In [19]:
data3.shape

AttributeError: 'list' object has no attribute 'shape'

In [20]:
data2.shape

AttributeError: 'list' object has no attribute 'shape'

In [21]:
arr2.ndim

2

In [22]:
arr2.shape

(2, 4)

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zero(3,6)

AttributeError: module 'numpy' has no attribute 'zero'

In [25]:
np.zeros(3,6)

TypeError: data type not understood

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,3,2))

array([[[1.30975919e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [2.22522596e-306, 1.71868941e+185]],

       [[7.96133154e-042, 1.80062288e+185],
        [3.73388839e-033, 1.10844917e-047],
        [3.62955188e+179, 4.66554854e-062]]])

In [28]:
np.arrange(15)

AttributeError: module 'numpy' has no attribute 'arrange'

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr=np.array([[1,2,3],[4,5,6]])

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
arr=np.arange(10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

5

In [37]:
arr[5:8]=12

In [38]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [39]:
arr_slice=arr[5:8]

In [40]:
arr_slice

array([12, 12, 12])

In [41]:
arr_slice[1]=123
arr_slice

array([ 12, 123,  12])

In [42]:
arr

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [43]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
array2d[1:,:2]

NameError: name 'array2d' is not defined

In [45]:
array2d[:1,2:]

NameError: name 'array2d' is not defined

In [46]:
array2d[:1, 2:]

NameError: name 'array2d' is not defined

In [47]:
array2d[:2, 1:]

NameError: name 'array2d' is not defined

In [48]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [50]:
arr2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [51]:
arr2d[:2,2]

array([3, 6])

In [52]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [53]:
arr2d[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [57]:
arr.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [58]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
arr.T.T

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])